language: java
jdk:
 - oraclejdk8
 - oraclejdk11
before_install:
 - wget https://raw.githubusercontent.com/opendaylight/odlparent/master/settings.xml; cp ./settings.xml $HOME/.m2/settings.xml
script: mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'

